### ISSUE TITLE
useAccessToken allows all refresh tokens as a substitute.

### ISSUE THREAD

**Issue by wesamjabali** [dkantereivin/nest-nuxt-starter#1]
The current implementation of useAccessToken allows the user to substitute their Auth header with a refresh token, essentially using it as their access token and bypassing the access tokens' expiration. This means a user can bypass all the security in place for as long as the refresh token lasts.

I recommend you add a check in useAccessToken that it actually _is_ an access token. For example, you can make sure the fingerprint hash does not exist in the decoded token.

**Comment by dkantereivin** [comment]
This looks legit. Thanks for the tip, will correct asap.
